people = ({'RR':'ryan.robertson', 
               'DR':'derek.russell', 
               'KG':'kelly.galway',
               'OT':'orang.towfig', 
               'JNor':'jeff.norman', 
               'JNei':'jonathan.neill',
               'GC':'grant.conroy',
               'BL':'rebecca.luke',
               'MMi':'martha.mitherakis',
               'GM':'greg.macdonald',
               'RP':'roberto.pavan',
               'JM':'joey.mikawoz',
               'PV':'pierre.vaillancourt',
               'ROB':'ralph.beyer',
               'MRM':'mike.morgan',
               'JB':'joey.bennett',
               'DZ':'dan.zavoral',
               'MH':'michael.ho', 
               'RG2':'rob.geisthardt',
               'KF':'kyle.ferguson',
               'DH':'dan.harney',
               'DF':'demetrios.fotiou'
              })
    
emails = {key: val + '@powerex.com' for key, val in people.items()}
